# pytest.ini
[pytest]
python_files = *_tests.py test_*.py   # Sets rules for test files
python_classes = Test*               # Sets rules for class names
python_functions = test_*            # Sets rules for function names