# pytest.ini
[pytest]
python_files = *_tests.py test_*.py   # Sets rules for test files
python_classes = Test*               # Sets rules for class names
python_functions = test_*            # Sets rules for function names
markers =
    regression: Markers for regression tests.
    registration: Markers for tests related to user registration.
    authorization: Markers for tests related to user authorization.
    courses: Markers for course-related tests.